# Generated by Django 3.0.8 on 2020-07-25 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoVenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estadoVenta', models.CharField(max_length=50)),
                ('activo', models.BooleanField()),
            ],
        ),
    ]
